<div id="contact-ro">
	<div id="form">
		<img src="IMG/4d373c62-acb2-4215-9f0c-d74b92e3536c-fadb0362-e723-4ab1-868d-9e256437ef3e-v1.png" alt="contact me">
		<h2 class="sentence">Ce vreți să</h2>
		<div class="rotate">
			<span>codez</span>
			<span>programez</span>
			<span>dezvolt</span>
			<span>construiesc</span>
			<span>creez</span>
		</div>
		<h2 class="sentence">pentru dumneavoastră astăzi ?</h2>
		<form>
			<ul class="form-group">
		        <li>
		        	<span class="icon-case"><i class="fa fa-male"></i></span>
		    		<input type="text" name="name" id="name" placeholder="Nume și prenume." data-rule="required" data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
			    </li>
			    <br/><br/>
			    <li>
			    	<span class="icon-case"><i class="fas fa-envelope"></i></span>
		    		<input type="text" name="mail" id="mail" data-rule="required" placeholder="E-mail." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
			    </li>
			   	<br/><br/>
		       	<li>
		       		<span class="icon-case"><i class="fas fa-university"></i></span>
		    		<input type="text" name="city" id="city" data-rule="required" placeholder="Orașul și țara." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
		       	</li>
		       	<br/><br/>
		   		<li>
		   			<span class="icon-case"><i class="fas fa-comment-alt"></i></span>
		    		<input type="text" name="object" id="object" data-rule="required" placeholder="Subiect." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
		   		</li>
		   		<br/><br/>
			   	<li>
			   		<span class="icon-case"><i class="fas fa-comments"></i></span>
		    		<textarea type="text" name="message" id="message" data-rule="required" placeholder="Mesaj." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."></textarea>
			   	</li>
			</ul>
			<br>
			<div class="buttons">
				<button type="reset" name="button">Anula</button>
				<button type="submit" name="button">Trimite</button>
			</div>
		</form>
	</div>
	<div id="downloads">
		<div id="downloads-1">
			<img src="IMG/80449733-5883-4546-98ef-8c56880403de-d36908f7-654c-401e-b136-03c07f344c42-v1.png">
			<h1><?= $downloadcv ;?></h1>
		</div>
		<div id="downloads-2">
			<h1><?= $selectalanguage ;?></h1>
			<br/>
			<select>
				<option disabled="disabled" selected="selected" value="0">-</option>
				<?php foreach($languages as $language): ?>
					<option value="<?= $language['parametre_url'] ?>"><?php $explode = explode(' ', $language['Nom'], 5);
						echo $explode[$number] ;?></option>
				<?php endforeach; ?>
			</select>
		</div>
		<div id="downloads-3">
			<h1>2. Télécharger</h1>
		</div>
	</div>
</div>