<div id="contact-fr">
	<div id="form">
		<img src="IMG/4d373c62-acb2-4215-9f0c-d74b92e3536c-fadb0362-e723-4ab1-868d-9e256437ef3e-v1.png" alt="contact me">
		<h2 class="sentence">Que voulez-vous que je</h2>
		<div class="rotate">
		  <span>code</span>
		  <span>programme</span>
		  <span>développe</span>
		  <span>builde</span>
		  <span>crée</span>
		</div>
		<h2 class="sentence">pour vous aujourd'hui ?</h2>
		<form method="POST" action="PHP/sendemail.php?lang=fr">
			<ul class="form-group">
		        <li>
		        	<span class="icon-case"><i class="fa fa-male"></i></span>
			    	<input type="text" name="name" placeholder="Nom et prénom." data-rule="required" data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
			    </li>
			    <br/><br/>
			    <li>
			    	<span class="icon-case"><i class="fas fa-envelope"></i></span>
			    	<input type="text" name="email" id="email" data-rule="required" placeholder="E-mail." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
			    </li>
			   	<br/><br/>
		       	<li>
		       		<span class="icon-case"><i class="fas fa-university"></i></span>
			    	<input type="text" name="city" id="city" data-rule="required" placeholder="Ville et pays." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
		       	</li>
		       	<br/><br/>
		   		<li>
		   			<span class="icon-case"><i class="fas fa-comment-alt"></i></span>
			    	<input type="text" name="object" id="object" data-rule="required" placeholder="Objet." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
		   		</li>
		   		<br/><br/>
			   	<li>
			   		<span class="icon-case"><i class="fas fa-comments"></i></span>
			    	<textarea type="text" name="message" id="message" data-rule="required" placeholder="Message."></textarea>
			   	</li>
			</ul>
			<br>
			<div class="buttons">
				<button type="reset" name="reset">Annuler</button>
				<button type="submit" name="submit">Envoyer</button>
			</div>
		</form>
	</div>
	<div id="downloads">
		<div id="downloads-1">
			<img src="IMG/80449733-5883-4546-98ef-8c56880403de-d36908f7-654c-401e-b136-03c07f344c42-v1.png">
			<h1><?= $downloadcv ;?></h1>
		</div>
		<div id="downloads-2">
			<h1>Télécharger</h1>
			<a href="CV-s/CV-FR.pdf" download><img src="CV-s/pic-cvfr.png"></a>
		</div>
	</div>
</div>