<div id="contact-de">
	<div id="form">
		<img src="IMG/4d373c62-acb2-4215-9f0c-d74b92e3536c-fadb0362-e723-4ab1-868d-9e256437ef3e-v1.png" alt="contact me">
		<h2 class="sentence">Was kann ich für euch</h2>
		<div class="rotate">
			<span>schreiben</span>
			<span>programmieren</span>
			<span>entwickeln</span>
			<span>erstellen</span>
			<span>kodieren</span>
		</div>
		<h2 class="sentence">?</h2>
		<form method="POST" action="PHP/sendemail.php?lang=de">
			<ul class="form-group">
		        <li>
		        	<span class="icon-case"><i class="fa fa-male"></i></span>
			    	<input type="text" name="name" id="name" placeholder="Name und Vorname." data-rule="required" data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
			    </li>
			    <br/><br/>
			    <li>
			    	<span class="icon-case"><i class="fas fa-envelope"></i></span>
			    	<input type="text" name="email" id="email" data-rule="required" placeholder="E-mail." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
			    </li>
			   	<br/><br/>
		       	<li>
		       		<span class="icon-case"><i class="fas fa-university"></i></span>
			    	<input type="text" name="city" id="city" data-rule="required" placeholder="Stadt und Land." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
		       	</li>
		       	<br/><br/>
		   		<li>
		   			<span class="icon-case"><i class="fas fa-comment-alt"></i></span>
			    	<input type="text" name="object" id="object" data-rule="required" placeholder="Betreff." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."/>
		   		</li>
		   		<br/><br/>
			   	<li>
			   		<span class="icon-case"><i class="fas fa-comments"></i></span>
			    	<textarea type="text" name="message" id="message" data-rule="required" placeholder="Nachricht." data-msg="Vérifiez votre saisie sur les champs : Le champ 'Nom' doit être renseigné."></textarea>
			   	</li>
			</ul>
			<br>
			<div class="buttons">
				<button type="reset" name="button">Abbrechen</button>
				<button type="submit" name="button">Absenden</button>
			</div>
		</form>
	</div>
	<div id="downloads">
		<div id="downloads-1">
			<img src="IMG/80449733-5883-4546-98ef-8c56880403de-d36908f7-654c-401e-b136-03c07f344c42-v1.png">
			<h1><?= $downloadcv ;?></h1>
		</div>
		<div id="downloads-2">
			<h1>Es tut mir Leid, aber mein Lebenslauf noch nicht in Deutsch verfügbar ist.</h1>
		</div>
	</div>
</div>