<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Curriculum Vitae</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="CSS/index.css">
	<link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Indie+Flower|Fredericka+the+Great|EB+Garamond|Charmonman|Crimson+Text" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  	<link rel="stylesheet" href="//resources/demos/style.css">
	<link rel="icon" type="image/png" sizes="16x16" href="IMG/favicon_package_v0.16/favicon.ico">
  	<link rel="stylesheet" href="/resources/demos/style.css">
	<script src="JS/slides/jquery.flexslider.js"></script>
	<script src="https://code.jquery.com/jquery-1.9.1.js"></script>
  	<script src="https://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  	<script src="JS/index.js"></script>
</head>
<body>
	<header>
		<div id=lang>
			<ul>
				<?php foreach($languages as $language): ?>
					<li>
						<a href="index.php?lang=<?= $language['parametre_url'] ?>">
						<img src="IMG/<?= $language['image']?>">
						</a>
					</li>
					<h5>
						<?php explode_and_echo(' ', $language['nom'], $number) ;?>
					</h5>
				<?php endforeach; ?>
			</ul>
		</div>
		<div id="presentation">
			<div id="title">
				<h1>Maxime J.</h1>
				<p><?= $introduction1 ;?></p>
				<p><?= $introduction4 ;?></p>
			</div>
			<nav id="menu">
				<ul>
					<li>
						<a href="#about"><?= $about ;?></a>
					</li>
					<li>
						<a href="#competences"><?= $competences ;?></a>
					</li>
					<li>
						<a href="#portfolio"><?= $portfolio ;?></a>
					</li>
					<li>
						<a href="#diplomas"><?= $diplomas ;?></a>
					</li>
					<li>
						<a href="#contact"><?= $contact ;?></a>
					</li>
					<?php foreach($informatics as $informatic): ?>
						<li>
							<a href="#informatic"><?= "#" .$informatic['nom']?></a>
						</li>
					<?php endforeach; ?>
					<?php foreach($languages as $language): ?>
						<li>
							<a href="#linguistic"><?= "<span>". "#" . "</span>" ;?>
								<?php explode_and_echo(' ', $language['nom'], $number) ;?>
							</a>
						</li>
					<?php endforeach; ?>
				</ul>
			</nav>
		</div>
	</header>
	<script src="https://www.w3counter.com/tracker.js?id=128768"></script>
	<main>
	
		<div id="about">
			<h1><?= $about ;?></h1>
			<div id="introduction-me">
				<img src="IMG/moi.png">
			</div>
			<div id="introduction-l">
				<div class="introduction-list">
					<img src="IMG/1055686.svg">
					<h4><?= $introduction1 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/174249.svg">
					<h4><?= $introduction2 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/149059.svg">
					<a href="https://www.google.fr/maps/place/34970+Lattes/@43.5658978,3.8585773,12.35z/data=!4m5!3m4!1s0x12b6b003830534e9:0x4078821166ac700!8m2!3d43.567296!4d3.896473" target="_blank"><h4><?= $introduction3 ?></h4></a>
				</div>
				<div class="introduction-list">
					<img src="IMG/616487.svg">
					<h4><?= $introduction4 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/java-4.svg">
					<h4><?= $introduction5 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/321817.svg">
					<h4><a href="mailto:maxime.j.sfr@free.fr">maxime.j.pro@sfr.fr</a></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/201623.svg">
					<h4><?= $introduction7 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/263381.svg">
					<h4><?= $introduction8 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/178148.svg">
					<h4><?= $introduction9 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/1137432.png">
					<h4><?= $introduction10 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/1142886.svg">
					<h4><?= $introduction11 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/861506.svg">
					<h4><?= $introduction12 ?></h4>
				</div>
			</div>
		</div>
		
		<div id="competences">
			<h1><?= $competences ?></h1>
			<div id="informatic">
				<div class="left">
				    <div class="hex-row">
				    	<?php foreach($tops as $top): ?>
						<div class="hex" value="<?= $top['id'] ?>">
				        	<div class="top"></div>
				        	<div class="middle"><img src="IMG/<?= $top['image'] ?>"></div>
				        	<div class="bottom"></div>
				        </div>
						<?php endforeach; ?>
				    </div>
				    <div class="hex-row even">
				        <?php foreach($mids as $mid): ?>
						<div class="hex" value="<?= $mid['id'] ?>">
				        	<div class="top"></div>
				        	<div class="middle"><img src="IMG/<?= $mid['image'] ?>"></div>
				        	<div class="bottom"></div>
				        </div>
						<?php endforeach; ?>
				    </div>
				    <div class="hex-row">
				        <?php foreach($bottoms as $bottom): ?>
						<div class="hex" value="<?= $bottom['id'] ?>">
				        	<div class="top"></div>
				        	<div class="middle"><img src="IMG/<?= $bottom['image'] ?>"></div>
				        	<div class="bottom"></div>
				        </div>
						<?php endforeach; ?>
				    </div>
				</div>
				<div id="instructions-1">
					<?= $instructions ;?>
					<br/>
					<ul class="arrow">
						<?php for ($i=0; $i <4 ; $i++) {
							echo '<li></li>'; }
						?>
					</ul>
				</div>
				<div class="right">
					<?php foreach($informatics as $informatic): ?>
					    <div class="details" value="<?= $informatic['id'] ?>">
				    		<div class="details-title">
				    			<h3><?= str_replace("_", " ", $informatic['nom']) ;?></h3>
				    		</div>
				    		<div class="details-title">
				    			<p>
				    				<?= "« " ;?>
						    		<?php explode_and_echo('***', $informatic['details'], $number) ;?>
						    		<?= " »" ;?>
						    		<a href="<?php explode_and_echo('***', $informatic['source'], $number) ;?>" target="_blank"><sup>[réf.]</sup></a>
					    		</p>
				    		</div>
				    		<div class="progress">
								<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<?= $informatic['progress'] ?>" aria-valuemin="0" aria-valuemax="100" style="width:<?= $informatic['progress'] ?>%">
									<?= $informatic['progress'] ?> %
								</div>
				    		</div>
					    </div>
					<?php endforeach; ?>
				</div>
			</div>
			<div id="linguistic">
				<div class="left">
				    <div class="hex-row">
				    	<?php foreach($languagestops as $languagestop): ?>
							<div class="hex" value="<?= $languagestop['id'] ?>">
					        	<div class="top"></div>
					        	<div class="middle"><img src="IMG/<?= $languagestop['image'] ?>"></div>
					        	<div class="bottom"></div>
					        </div>
						<?php endforeach; ?>
				    </div>
				    <div class="hex-row even">
				        <?php foreach($languagesbottoms as $languagesbottom): ?>
							<div class="hex" value="<?= $languagesbottom['id'] ?>">
					        	<div class="top"></div>
					        	<div class="middle"><img src="IMG/<?= $languagesbottom['image'] ?>"></div>
					        	<div class="bottom"></div>
					        </div>
						<?php endforeach; ?>
					</div>
				</div>
				<div id="instructions-2">
					<?= $instructions ;?>
					<br/>
					<ul class="arrow">
						<?php for ($i=0; $i <4 ; $i++) {
							echo '<li></li>'; }
						?>
					</ul>
				</div>
				<div class="right">
					<?php foreach($languages as $language): ?>
					    <div class="details" value="<?= $language['id'] ?>">
				    		<div class="details-title">
				    			<h3>
				    				<?php explode_and_echo(' ', $language['nom'], $number) ;?>
								</h3>
				    		</div>
				    		<div class="details-title">
				    			<p>
				    				<?= "« " ;?>
						    		<?php explode_and_echo('***', $language['details'], $number) ;?>
						    		<?= " »" ;?>
						    		<a href="<?php explode_and_echo('***', $language['source'], $number) ;?>" target="_blank"><sup>[réf.]</sup></a>
				    			</p>
				    		</div>
				    		<div class="progress">
    								<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<?= $language['progress'] ?>" aria-valuemin="0" aria-valuemax="100" style="width:<?= $language['progress'] ?>%">
      								<?= $language['progress'] ?>%</div>
			    			</div>
					    </div>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
		<div id="portfolio">
			<h1><?= $portfolio ?></h1>
			<div id="buttons">
				<button value="realisations"></button>
				<button value="pictures"></button>
				<button value="others"></button>
				<button value="works"></button>
				<button value="elearning"></button>
			</div>
			<div id="realisations">
				<?php foreach($realisations as $realisation): ?>
					<figure>
						<a href="<?= $realisation['url'] ?>" target="_blank"><img src="IMG/<?= $realisation['photo'] ?>"></a>
						<h1><?= $realisation['nom'] ?></h1>
					</figure>
				<?php endforeach; ?>
			</div>
			<div id="pictures">
				<?php foreach($voyages as $voyage): ?>
					<figure>
						<img src="IMG/<?= $voyage['image'] ?>">
						<h1><?= $voyage['titre'] . " ". $voyage['annee'] ;?></h1>
					</figure>
				<?php endforeach; ?>
			</div>
			<div id="canvas">
				<?php include "canvas-" . $lang . ".phtml"; ?>
			</div>
			<div id="works">
				<?php foreach($works as $work): ?>
					<a href="<?= $work['URL']?>" target="_blank">
						<img src="IMG/<?= $work['logo'] ?>">
						<legend>
							<?php explode_and_echo('.', $work['name'], $number) ;?>
							<div class="details">
								<?php echo $work['language'] ?>
							</div>
						</legend>
					</a>
				<?php endforeach; ?>
			</div>
			<div id="elearning">
			  <ul>
			  	<?php foreach($elearning as $e): ?>
			    <li>
			      <img src="elearning/<?= $e['url_image'] ?>"/>
			    </li>
			    <?php endforeach; ?>
			  </ul>
			</div>
		</div>
		<div id="diplomas">
			<h1><?= $diplomas ?></h1>
			<div class="timeline">
				<?php foreach($diplomasleft as $diplomaleft): ?>
			  	<div class="diplomas-left">
				    <div class="content">
					    <h2>
					    	<?php explode_and_echo('**', $diplomaleft['month'], $number) ;?>
					    	<?= $diplomaleft['year'] ;?>
					    </h2>
					    <h3>
					    	<?php explode_and_echo('**', $diplomaleft['title'], $number) ;?>
					    </h3>
					    <img src="IMG/<?= $diplomaleft['image'] ;?>">
					    <p><?= "« ".$diplomaleft['description']. " »";?>
					    <a href="<?= $diplomaleft['reference'] ;?>" target="_blank"><sup>[réf.]</sup></a>
					    </p>
				    </div>
			  	</div>
			  	<?php endforeach; ?>
			</div>
			<div id="vertical-line">
				<?php for ($i=0; $i < 7; $i++) {
					echo '<div class="circle">'.'</div>';
					;}
				?>
			</div>
			<div class="timeline">
				<?php foreach($diplomasright as $diplomaright): ?>
				<div class="diplomas-right">
				    <div class="content">
				    	<h2>
				    		<?php explode_and_echo('**', $diplomaright['month'], $number) ;?>
				    		<?= $diplomaright['year'] ;?>
					    </h2>
					    <h3>
					    	<?php explode_and_echo('**', $diplomaright['title'], $number) ;?>
					    </h3>
					    <img src="IMG/<?= $diplomaright['image'] ;?>">
					    <p><?= "« ".$diplomaright['description']." »" ;?>
					    <a href="<?= $diplomaright['reference'] ;?>" target="_blank"><sup>[réf.]</sup></a>
					    </p>
				    </div>
				</div>
				<?php endforeach; ?>
			</div>
			<div class="chat-box">
				<div class="buttons">
					<button>X</button>
				</div>
			  	<div class="open">
				  	<img src="IMG/214e2e2c-3a98-46f6-9b61-50c57a0d8fca-fadb0362-e723-4ab1-868d-9e256437ef3e-v1.png">
				  	 <!-- ON PASSE LES VARIABLES PHP EN JQUERY -->
				  	<script>
					  	var chatbox1 = <?php echo json_encode($chatbox1); ?>;
			 			var chatbox2 = <?php echo json_encode($chatbox2); ?>;
					</script>
				  	<h4><?= $chatbox1 ?></h4>
					<div class="box">
						<?php include "form-" . $lang . ".phtml" ;?>
					</div>
				</div>
		  	</div>
		</div>
		<div id="contact">
			<h1><?= $contact ?></h1>
			<?php include "contact-" . $lang . ".phtml" ;?>
		</div>
	</main>
	<footer>
		<div id="social">
			<h4><?= $networks ;?></h4>
			<div class="circle">
				<?php foreach($social as $socials): ?>
					<a href="<?= $socials['url'] ?>" target="_blank" title="<?= $socials['nom'] ?>";?><?= $socials['image']?></a>
				<?php endforeach; ?>
				<i class="fab fa-snapchat-ghost"></i>
			</div>
		</div>
		<div id="dialog-message">
		    <?= $snapchat ;?>
		</div>
		<ul id="credits">
			<li><b><?= $credits ?></b></li>
			<li>© 2018 Codeur et Directeur de la publication</li>
			<li><i class="fas fa-user-circle"></i> Maxime Jacquette</li>
			<li><i class="fas fa-envelope-open"></i> maxime.j.sfr@free.fr</li>
			<li><i class="fas fa-phone-volume"></i> +33 7 83 89 96 37</li>
			<li><i class="fas fa-location-arrow"></i> Lattes, France</li>
			<li>Mis en ligne par Heroku</li>
			<li></li> 
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</footer>
</body>
</html>