<!DOCTYPE html>
<html lang="fr">
<head>
	<title>Curriculum Vitae</title>
	<link rel="stylesheet" type="text/css" href="CSS/index.css">
	<link href="https://fonts.googleapis.com/css?family=Architects+Daughter|Indie+Flower|Fredericka+the+Great|EB+Garamond|Charmonman|Crimson+Text" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
	<meta charset="utf-8">
  	<meta name="viewport" content="width=device-width, initial-scale=1">
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  	<link rel="stylesheet" href="/resources/demos/style.css">
  	<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  	<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  	<script src="JS/slides/jquery.flexslider.js"></script>
</head>
<body>
	<header>
		<div id=lang>
			<ul>
				<?php foreach($languages as $language): ?>
					<li>
						<a href="index.php?lang=<?= $language['parametre_url'] ?>">
						<img src="IMG/<?= $language['Image']?>">
						</a>
					</li>
					<h5>
						<?php $explode = explode(' ', $language['Nom'], 5);
						echo $explode[$number] ;?>
					</h5>
				<?php endforeach; ?>
			</ul>
		</div>
		<div id="presentation">
			<div id="title">
				<h1>Maxime J.</h1>
				<p><?= $introduction1 ;?></p>
				<p><?= $introduction4 ;?></p>
			</div>
			<nav id="menu">
				<ul>
					<li>
						<a href="#about"><?= $about ;?></a>
					</li>
					<li>
						<a href="#competences"><?= $competences ;?></a>
					</li>
					<li>
						<a href="#portfolio"><?= $portfolio ;?></a>
					</li>
					<li>
						<a href="#diplomas"><?= $diplomas ;?></a>
					</li>
					<li>
						<a href="#contact"><?= $contact ;?></a>
					</li>
					<br/><br/>
					<?php foreach($informatics as $informatic): ?>
					<li>
						<a href="#informatic"><?= "#" .$informatic['Nom']?></a>
					</li>
					<?php endforeach; ?>
					<br/><br/>
					<?php foreach($languages as $language): ?>
					<li>
						<a href="#linguistic"><?= "<span>". "#" . "</span>" ;?>
							<?php $explode = explode(' ', $language['Nom'], 5);
							echo $explode[$number] ;?>
						</a>
					</li>
					<?php endforeach; ?>
				</ul>
			</nav>
		</div>
	</header>
	<main>
		<div id="about">
			<h1><?= $about ;?></h1>
			<div id="introduction-me">
				<img src="IMG/moi.png">
			</div>
			<div id="introduction-l">
				<div class="introduction-list">
					<img src="IMG/1055686.svg">
					<h4><?= $introduction1 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/174249.svg">
					<h4><?= $introduction2 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/149059.svg">
					<h4><?= $introduction3 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/616487.svg">
					<h4><?= $introduction4 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/552456.svg">
					<h4><?= $introduction5 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/321817.svg">
					<h4><a href="mailto:maxime.j.pro@free.fr">maxime.j.pro@free.fr</a></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/201623.svg">
					<h4><?= $introduction7 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/263381.svg">
					<h4><?= $introduction8 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/178148.svg">
					<h4><?= $introduction9 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/1137432.png">
					<h4><?= $introduction10 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/1142886.svg">
					<h4><?= $introduction11 ?></h4>
				</div>
				<div class="introduction-list">
					<img src="IMG/861506.svg">
					<h4><?= $introduction12 ?></h4>
				</div>
			</div>
		</div>
		<div id="competences">
			<h1><?= $competences ?></h1>
			<div id="informatic">
				<div class="left">
				    <div class="hex-row">
				    	<?php foreach($tops as $top): ?>
						<div class="hex" value="<?= $top['iD'] ?>">
				        	<div class="top"></div>
				        	<div class="middle"><img src="IMG/<?= $top['Image'] ?>"></div>
				        	<div class="bottom"></div>
				        </div>
						<?php endforeach; ?>
				    </div>
				    <div class="hex-row even">
				        <?php foreach($mids as $mid): ?>
						<div class="hex" value="<?= $mid['iD'] ?>">
				        	<div class="top"></div>
				        	<div class="middle"><img src="IMG/<?= $mid['Image'] ?>"></div>
				        	<div class="bottom"></div>
				        </div>
						<?php endforeach; ?>
				    </div>
				    <div class="hex-row">
				        <?php foreach($bottoms as $bottom): ?>
						<div class="hex" value="<?= $bottom['iD'] ?>">
				        	<div class="top"></div>
				        	<div class="middle"><img src="IMG/<?= $bottom['Image'] ?>"></div>
				        	<div class="bottom"></div>
				        </div>
						<?php endforeach; ?>
				    </div>
				</div>
				<div id="instructions-1">
					<?= $instructions ;?>
					<br/>
					<ul class="arrow">
						<?php for ($i=0; $i <4 ; $i++) {
							echo '<li></li>'; }
						?>
					</ul>
				</div>
				<div class="right">
				<?php foreach($informatics as $informatic): ?>
				    <div class="details" value="<?= $informatic['iD'] ?>">
			    		<div class="details-title">
			    			<h3><?= str_replace("_", " ", $informatic['Nom']) ;?></h3>
			    		</div>
			    		<div class="details-title">
			    			<p>
					    		<?= "« " . $informatic['Details'] . " »" ;?>
					    		<a href="<?= $informatic['source'] ;?>" target="_blank"><sup>[réf.]</sup></a>
				    		</p>
			    		</div>
			    		<div class="progress">
							<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<?= $informatic['progress'] ?>" aria-valuemin="0" aria-valuemax="100" style="width:<?= $informatic['progress'] ?>%">
								<?= $informatic['progress'] ?> %
							</div>
			    		</div>
				    </div>
				<?php endforeach; ?>
				</div>
			</div>
			<div id="linguistic">
				<div class="left">
				    <div class="hex-row">
				    	<?php foreach($languagestops as $languagestop): ?>
							<div class="hex" value="<?= $languagestop['iD'] ?>">
					        	<div class="top"></div>
					        	<div class="middle"><img src="IMG/<?= $languagestop['Image'] ?>"></div>
					        	<div class="bottom"></div>
					        </div>
						<?php endforeach; ?>
				    </div>
				    <div class="hex-row even">
				        <?php foreach($languagesbottoms as $languagesbottom): ?>
							<div class="hex" value="<?= $languagesbottom['iD'] ?>">
					        	<div class="top"></div>
					        	<div class="middle"><img src="IMG/<?= $languagesbottom['Image'] ?>"></div>
					        	<div class="bottom"></div>
					        </div>
						<?php endforeach; ?>
					</div>
				</div>
				<div id="instructions-2">
					<?= $instructions ;?>
					<br/>
					<ul class="arrow">
						<?php for ($i=0; $i <4 ; $i++) {
							echo '<li></li>'; }
						?>
					</ul>
				</div>
				<div class="right">
					<?php foreach($languages as $language): ?>
					    <div class="details" value="<?= $language['iD'] ?>">
				    		<div class="details-title">
				    			<h3><?php $explode = explode(' ', $language['Nom'], 5);
									echo $explode[$number] ;?>
								</h3>
				    		</div>
				    		<div class="details-title">
				    			<p>
					    			<?= "« " . $language['Details'] . " »" ;?>
					    			<a href="<?= $language['source'] ;?>" target="_blank"><sup>[réf.]</sup></a>
				    			</p>
				    		</div>
				    		<div class="progress">
    								<div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="<?= $language['progress'] ?>" aria-valuemin="0" aria-valuemax="100" style="width:<?= $language['progress'] ?>%">
      								<?= $language['progress'] ?>%</div>
			    			</div>
					    </div>
					<?php endforeach; ?>
				</div>
			</div>
		</div>
		<div id="portfolio">
			<h1><?= $portfolio ?></h1>
			<div id="buttons">
				<button value="realisations"></button>
				<button value="pictures"></button>
				<button value="others"></button>
				<button value="works"></button>
			</div>
			<div id="realisations">
				<?php foreach($realisations as $realisation): ?>
					<a href=""><img src="IMG/<?= $realisation['Photo'] ?>"></a>
				<?php endforeach; ?>
			</div>
			<div id="pictures">
				<ul>
					<?php foreach($voyages as $voyage): ?>
						<img src="IMG/<?= $voyage['Image'] ?>">
					<?php endforeach; ?>
				</ul>
			</div>
			<div id="canvas">
				<?php include "canvas-" . $lang . ".phtml"; ?>
			</div>
			<div id="works">
				<?php foreach($works as $work): ?>
					<a href="IMG/<?= $work['URL']?>" target="_blank">
						<img src="IMG/<?= $work['Image'] ?>">
						<legend>
							<?php $explode = explode('.', $work['Nom'], 5);
								echo $explode[$number]
							;?>
						</legend>
					</a>
				<?php endforeach; ?>
			</div>
		</div>
		<div id="diplomas">
			<h1><?= $diplomas ?></h1>
			<div class="timeline">
				<?php foreach($diplomasleft as $diplomaleft): ?>
			  	<div class="diplomas-left">
			  		<div class="arrow-right">
			    	</div>
				    <div class="content">
					    <h2><?= $diplomaleft['Month']." ".$diplomaleft['Year'] ;?></h2>
					    <h3><?= $diplomaleft['Title'] ;?></h3>
					    <img src="IMG/<?= $diplomaleft['Image'] ;?>">
					    <p><?= "« ".$diplomaleft['Description']. " »";?>
					    <a href="<?= $diplomaleft['reference'] ;?>" target="_blank"><sup>[réf.]</sup></a>
					    </p>
				    </div>
			  	</div>
			  	<?php endforeach; ?>
			</div>
			<div id="vertical-line">
				<?php for ($i=0; $i < 7; $i++) {
					echo '<div class="circle">'.'</div>';}
				?>
			</div>
			<div class="timeline">
				<?php foreach($diplomasright as $diplomaright): ?>
				<div class="diplomas-right">
			  		<div class="arrow-left">
			    	</div>
				    <div class="content">
				    	<h2><?= $diplomaright['Month']." ".$diplomaright['Year'] ;?></h2>
					    <h3><?= $diplomaright['Title'] ;?></h3>
					    <img src="IMG/<?= $diplomaright['Image'] ;?>">
					    <p><?= "« ".$diplomaright['Description']." »" ;?>
					    <a href="<?= $diplomaright['reference'] ;?>" target="_blank"><sup>[réf.]</sup></a>
					    </p>
				    </div>
				</div>
				<?php endforeach; ?>
			</div>
		</div>
		<div class="chat-box">
			<div class="buttons">
				<button>X</button>
			</div>
		  	<div class="open">
			  	<img src="IMG/214e2e2c-3a98-46f6-9b61-50c57a0d8fca-fadb0362-e723-4ab1-868d-9e256437ef3e-v1.png">
			  	<!-- ON PASSE LES VARIABLES PHP EN JQUERY -->
			  	<script>
				  	var chatbox1 = <?php echo json_encode($chatbox1); ?>;
		 			var chatbox2 = <?php echo json_encode($chatbox2); ?>;
				</script>
			  	<h4><?= $chatbox1 ?></h4>
				<div class="box">
					<?php include "form-" . $lang . ".phtml" ;?>
				</div>
		  	</div>
		</div>
		<div id="contact">
			<h1><?= $contact ?></h1>
			<?php include "contact-" . $lang . ".phtml" ;?>
		</div>
	</main>
	<footer>
		<div id="social">
			<h4><?= $networks ;?></h4>
			<div class="circle">
				<?php foreach($social as $socials): ?>
					<a href="<?= $socials['URL'] ?>" target="_blank" title="<?= $socials['Nom'] ?>";?><?= $socials['Image']?></a>
				<?php endforeach; ?>
				<i class="fab fa-snapchat-ghost"></i>
			</div>
		</div>
		<div id="dialog-message">
		    <?= $snapchat ;?>
		</div>
		<ul id="credits">
			<li><b><?= $credits ?></b></li>
			<li>© 2018 Codeur et Directeur de la publication</li>
			<li><i class="fas fa-user-circle"></i> Maxime Jacquette</li>
			<li><i class="fas fa-envelope-open"></i> maxime.j.pro@free.fr</li>
			<li><i class="fas fa-phone-volume"></i> +33 7 83 89 96 37</li>
			<li><i class="fas fa-location-arrow"></i> 06400 Cannes</li>
			<li>Mis en ligne par FREE</li>
			<li>Siège Social de Free</li> 
			<li>8 Rue de la Ville-l’Évêque</li>
			<li>75008, Paris</li>
			<li>01 73 50 20 00</li>
		</ul>
	</footer>
	<script src="JS/index.js"></script>
</body>
</html>
