<!DOCTYPE html>
<html>
<head>
	<title>Curriculum Vitae</title>
	<link rel="stylesheet" type="text/css" href="../CSS/sendmessage.css">
	<link href="https://fonts.googleapis.com/css?family=Alegreya" rel="stylesheet">
</head>
<body>
	<?php 
	$name = "";
    $email = "";
    $city = "";
    $object = "";
    $message = "";
    $headers = "";
    
    //Mon adresse mail
    $to = "maxime.j.pro@free.fr";

	if (isset($_POST['name'])){
		//ANTI FAILLE XSS
		$name = htmlspecialchars($_POST['name']);
	};

	if (isset($_POST['email'])){
		//ANTI FAILLE XSS
		$email = htmlspecialchars($_POST['email']);
	};

	if (isset($_POST['city'])){
		//ANTI FAILLE XSS
		$city = htmlspecialchars($_POST['city']);
	};

	if (isset($_POST['object'])){
		//ANTI FAILLE XSS
		$object = htmlspecialchars($_POST['object']);
	};

	if (isset($_POST['message'])){
		//ANTI FAILLE XSS
		$message = htmlspecialchars($_POST['message']);
		$message = wordwrap($message, 70, "\r\n");
	};


	if (isset($_POST['email'])){
		//ANTI FAILLE XSS
		$from = htmlspecialchars($_POST['email']);
		$headers = "From:" . $from;
		$headers .= "\r\n";
	};

	$lang = "fr";
	if (isset($_GET['lang'])) {
	$lang = $_GET["lang"];
	}
	switch ($lang) {
	// FRANCAIS //
    case "fr":
    	$firstname = "Nom et prénom : ";
    	$youremail = "Votre mail : ";
    	$citycountry = "Ville et pays : ";
    	$subject = "Objet : ";
    	$yourmessage = "Message : ";
        $chat_box_message_success = "Votre message a été envoyé.";
        $chat_box_message_fail = "Le message n'a pu être envoyé car tous les champs sont requis.";
        $home = "Accueil";

        break;
    // ANGLAIS //
    case "en":
 		$firstname = "Name and firstname : ";
 		$youremail = "Your email : ";
 		$citycountry = "City and country : ";
 		$subject = "Subject : ";
 		$yourmessage = "Message : ";
        $chat_box_message_success = "Your message has been sent.";
        $chat_box_message_fail = "The message hasn't been sent because all fields are required.";
        $home = "Home";

        break;
    // ROUMAIN //
    case "ro":
    	$firstname = "Nume și prenume : ";
    	$youremail = "E-mail-ul dumneavoastră : ";
    	$citycountry = "Oraș și țară : ";
    	$subject = "Subiect : ";
    	$yourmessage = "Mesaj : ";
        $chat_box_message_success = "Mesajul dumneavoastră a fost trimis cu succes.";
        $chat_box_message_fail = "Mesajul nu a fost trimis, deoarece toate câmpurile sunt obligatorii.";
        $home = "Pagină principală";

        break;
    // ESPAGNOL //
    case "es":
    	$firstname = "Nombre y Apellido : ";
    	$youremail = "Su e-mail : ";
    	$citycountry = "Ciudad y país : ";
    	$subject = "Objeto : ";
    	$yourmessage = "Mensaje : ";
        $chat_box_message_success = "Su mensaje ha sido enviado correctamente.";
        $chat_box_message_fail = "El mensaje no se ha enviado porque se requieren todos los campos.";
        $home = "Inicio";

        break;
    
    case "de":
        $firstname = "Name und Vorname : ";
        $youremail = "Ihre E-Mail : ";
        $citycountry = "Stadt und Land : ";
        $subject = "Betreff : ";
        $yourmessage = "Nachricht : ";
        $chat_box_message_success = "Die Nachricht wurde erfolgreich abgeschickt.";
        $chat_box_message_fail = "Ihre Nachricht konnte nicht gesendet werden, weil Alle Felder notwendig sind.";
        $home = "Hauptseite";

        break;
	}
	?>
	<a href="../index.php?lang=<?= $lang ;?>">
		<img src="../IMG/1168681.svg"><?= $home ;?>
	</a>
	<?php if (!empty($_POST['name']) && !empty($_POST['email']) && !empty($_POST['city']) && !empty($_POST['object']) && !empty($_POST['message'])): ?>
    	<?php mail($to, $object, $message, $headers) ;?>
    	<div class="sendmessage">
	    	<img src='../IMG/2063b3b3-2054-4a07-83b6-0a10a04de771-e0e229cb-b694-4474-9d43-07fcf28055a6-v1.png'/>
	    	<h3><?= $chat_box_message_success ;?></h3>
	    	<h3><?= $firstname ;?></h3>
	    	<p><?= $name ;?></p>
	    	<h3><?= $youremail ;?></h3>
	    	<p><?= $email ;?></p>
	    	<h3><?= $citycountry ;?></h3>
	    	<p><?= $city ;?></p>
	    	<h3><?= $subject ;?></h3>
	    	<p><?= $object ;?></p>
	    	<h3><?= $yourmessage ;?></h3>
	    	<p><?= $message ;?></p>
	    </div>
   	<?php else: ?>
		<div class="sendmessage">
			<img src='../IMG/7ff91094-e4e4-496a-9975-c0b5f6ef26ef-e0e229cb-b694-4474-9d43-07fcf28055a6-v1.png'/>
			<h3><?= $chat_box_message_fail ;?></h3>
		</div>
	<?php endif ;?>
</body>
</html>